Repository hassio-addons/addon-wireguard, pull requests merged in 2021-11, with the labels that each got.

#171 Fixed typo
  wireguard/DOCS.md
Labels: documentation

#173 Migrate JSON config to YAML
  wireguard/build.json
  wireguard/build.yaml
  wireguard/config.json
  wireguard/config.yaml
Labels: refactor

#174 ⬆️ Upgrades go to 1.16.10-r0
  wireguard/Dockerfile
Labels: dependencies

#175 ⬆️ Upgrades add-on base image to 10.2.2
  wireguard/Dockerfile
  wireguard/build.yaml
Labels: dependencies

#176 ⬆️ Upgrades WireGuard Go to 0.0.20210424
  wireguard/Dockerfile
Labels: dependencies
